label: Berkas
display:
  default:
    display_title: Bawaan
    display_options:
      title: Berkas
      fields:
        filename:
          label: Nama
          separator: ', '
        filemime:
          label: 'Jenis MIME'
        filesize:
          label: Ukuran
        status:
          label: Status
          settings:
            format_custom_false: Sementara
            format_custom_true: Permanen
        changed:
          label: 'Tanggal diubah'
        count:
          label: 'Digunakan di'
        operations:
          label: Operasi
      pager:
        options:
          tags:
            next: 'Selanjutnya ›'
            previous: '‹ Sebelumya'
          expose:
            items_per_page_label: 'Jumlah item per halaman'
            items_per_page_options_all_label: '- Semua -'
            offset_label: Letak
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sortir dengan'
          sort_asc_label: 'Urutan turun'
          sort_desc_label: Desc
      filters:
        filename:
          expose:
            label: 'Nama berkas'
        filemime:
          expose:
            label: 'Jenis MIME'
        status:
          expose:
            label: Status
  page_1:
    display_options:
      menu:
        title: Berkas
  page_2:
    display_title: 'Penggunaan berkas'
    display_options:
      title: 'Penggunaan berkas'
      fields:
        entity_label:
          label: Entitas
        type:
          label: 'Jenis Entity'
        count:
          label: 'Jumlah penggunaan'
      pager:
        options:
          tags:
            next: 'Selanjutnya ›'
            previous: '‹ Sebelumya'
          expose:
            items_per_page_label: 'Jumlah item per halaman'
            items_per_page_options_all_label: '- Semua -'
            offset_label: Letak
      arguments:
        fid:
          exception:
            title: Semua
