name: drupal-ai
type: drupal11
docroot: web
php_version: "8.3"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
  - primary.ddev.site
  - site1.ddev.site
  - site2.ddev.site
use_dns_when_possible: true
